FROM python:3.9-slim

ENV PYTHONBUFFERED=1

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./

RUN chmod +x prestart.sh \
    && cp prestart.sh prestart.sh.bak \
    && tr -d '\r' < prestart.sh.bak > prestart.sh \
    && rm prestart.sh.bak

EXPOSE 5000

ENTRYPOINT ["/app/prestart.sh"]
CMD ["python", "app.py"]
