---
version: '3'

services:
  pg:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pg

volumes:
  pgdata:
